// A simple list of banned words for moderation. Add/remove as needed.
export const bannedWords = [
  "fuck",
  "shit",
  "bitch",
  "asshole",
  "bastard",
  "dick",
  "pussy",
  "cunt",
  "nigger",
  "faggot",
  "slut",
  "whore",
  "retard",
  "nigga",
  "cock",
  "cum",
  "suck my dick",
  "motherfucker",
  "douche",
  "twat",
  "wanker",
  "spastic",
  "fag",
  "rape",
  "rapist",
  "chink",
  "kike",
  "spic",
  "tranny",
  "fisting",
  "anal",
  "blowjob",
  "handjob",
  "porn",
  "porno",
  "pornography",
  "hentai",
  "incest",
  "molest",
  "molester",
  "pedophile",
  "paedophile",
  "child porn",
  "childporn",
  "beastiality",
  "bestiality",
  "zoophilia",
  "kill yourself",
  "kys",
  "suicide",
  "self harm",
  "self-harm",
  "cutting",
  "die bitch",
  "die cunt",
  "die nigger",
  "die faggot",
  "heil hitler",
  "hitler",
  "nazi",
  "gas the jews",
  "jew",
  "jews",
  "terrorist",
  "terrorism",
  "isis",
  "al qaeda",
  "al-qaeda",
  "taliban",
  "bomb",
  "explosives",
  "shoot",
  "shooting",
  "school shooting",
  "massacre",
  "mass murder",
  "serial killer",
  "serialkiller",
  "genocide",
  "lynch",
  "lynching",
  "shoot",
  "shooting",
  "school shooting",
  "school shooter",
  "schoolshooting",
  "schoolshooter",
  "stab",
  "stabbing",
  "bomb",
  "explosives",
  "terrorist",
  "terrorism",
  "isis",
  "al qaeda",
  "al-qaeda",
  "taliban",
  "jihad",
  "martyr",
  "martyrdom",
  "behead",
  "beheading",
  "decapitate",
  "decapitation",
  // Hate, extremism, Nazi, antisemitism
  "heil hitler",
  "hitler",
  "nazi",
  "nazism",
  "gas the jews",
  "gas the kikes",
  "gas the niggers",
  "jew",
  "jews",
  "kikes",
  "holocaust",
  "shoah",
  "final solution",
  "white power",
  "white supremacy",
  "white supremacist",
  "kkk",
  "klan",
  "neo-nazi",
  "neo nazi",
  "neo-nazism",
  "swastika",
  "stormfront",
  "14 words",
  "1488",
  // Miscellaneous
  "terror",
  "terrorize",
  "terrorising",
  "terrorizing",
  "abuse",
  "abusive",
  "abuser",
  "groom",
  "groomer",
  "grooming",
  "predator",
  "predatory",
  "stalker",
  "stalking",
  "creep",
  "creeper",
  "pervert",
  "perverted",
  "perversion",
  "scam",
  "scammer",
  "fraud",
  "fraudster",
  "phishing",
  "dox",
  "doxx",
  "doxxing",
  "doxing",
  "swat",
  "swatting",
  "blackmail",
  "extort",
  "extortion",
  "threat",
  "threaten",
  "threatening",
  "harass",
  "harassment",
  "bully",
  "bullying",
  "cyberbully",
  "cyberbullying",
  "troll",
  "trolling",
  "hate crime",
  "hatecrime",
  "hate speech",
  "hatespeech",
  "bigot",
  "bigotry",
  "racist",
  "racism",
  "sexist",
  "sexism",
  "homophobe",
  "homophobia",
  "transphobe",
  "transphobia",
  "misogynist",
  "misogyny",
  "misandrist",
  "misandry",
  "incel",
  "incels",
  "redpill",
  "red pill",
  "blackpill",
  "black pill",
  "whitepill",
  "white pill",
  "simp",
  "simping",
  "neckbeard",
  "nice guy",
  "niceguy",
  "nice-guy",
  "virgin",
  "loser",
  "beta male",
  "betamale",
  "beta-male",
  "alpha male",
  "alphamale",
  "alpha-male",
  "chad",
  "stacy",
  "roastie",
  "femoid",
  "femoid",
  "thot",
  "hoe",
  "harlot",
  "jezebel",
  "skank",
  "skanky",
  "gold digger",
  "golddigger",
  "gold-digger",
  "sugar daddy",
  "sugardaddy",
  "sugar-daddy",
  "sugar baby",
  "sugarbaby",
  "sugar-baby",
  "escort",
  "escort service",
  "escortservice",
  "camgirl",
  "cam girl",
  "camwhore",
  "cam whore",
  // Add more as needed for your use case
  "onlyfans",
  "only fans",
  "only-fans",
  "cam model",
  "cammodel",
  "cam-model",
  "webcam girl",
  "webcamgirl",
  "webcam-girl",
  "webcam boy",
  "webcamboy",
  "webcam-boy",
  "escort agency",
  "escortagency",
  "escort-agency",
  "prostitute",
  "prostitution",
  "john",
  "pimp",
  "pimping",
  "sex worker",
  "sexworker",
  "sex-worker",
  "sex work",
  "sexwork",
  "sex-work",
  "stripper",
  "stripping",
  "strip club",
  "stripclub",
  "strip-club",
  "lap dance",
  "lapdance",
  "lap-dance",
  "brothel",
  "brothels",
  "call girl",
  "callgirl",
  "call-girl",
  "call boy",
  "callboy",
  "call-boy",
  "escort boy",
  "escortboy",
  "escort-boy",
  "escort girl",
  "escortgirl",
  "escort-girl",
  "adult work",
  "adultwork",
  "adult-work",
  "escort directory",
  "escortdirectory",
  "escort-directory",
  "escort listings",
  "escortlistings",
  "escort-listings",
  "escort review",
  "escortreview",
  "escort-review",
  "escort forum",
  "escortforum",
  "escort-forum",
  "escort ads",
  "escortads",
  "escort-ads",
  "escort classified",
  "escortclassified",
  "escort-classified",
  "escort classifieds",
  "escortclassifieds",
  "escort-classifieds",
  "escort agency",
  "escortagency",
  "escort-agency",
  "prostitute",
  "prostitutes",
  "prostitution",
  "john",
  "johns",
  "pimp",
  "pimps",
  "pimping",
  "madam",
  "sex slave",
  "sexslave",
  "sex-slave",
  "sex trafficking",
  "sextrafficking",
  "sex-trafficking",
  "human trafficking",
  "humantrafficking",
  "human-trafficking",
  "child trafficking",
  "childtrafficking",
  "child-trafficking",
  "grooming",
  "groomer",
  "groomers",
  "child groomer",
  "childgroomer",
  "child-groomer",
  "child abuse",
  "childabuse",
  "child-abuse",
  "child molester",
  "childmolester",
  "child-molester",
  "child predator",
  "childpredator",
  "child-predator",
  "pedo",
  "pedos",
  "paedo",
  "paedos",
  "loli",
  "lolicon",
  "shotacon",
  "shota",
  "cp", // child porn abbreviation
  "nsfw",
  "nsfl",
  "bdsm",
  "bondage",
  "bdsm slave",
  "bdsm-slave",
  "bdsmslave",
  "bdsm master",
  "bdsm-master",
  "bdsmmaster",
  "bdsm dom",
  "bdsm-dom",
  "bdsmdom",
  "bdsm sub",
  "bdsm-sub",
  "bdsmsub",
  "dominatrix",
  "submissive",
  "dominant",
  "fetish",
  "fetishes",
  "kink",
  "kinky",
  "cumshot",
  "creampie",
  "bukkake",
  "gangbang",
  "orgy",
  "orgies",
  "threesome",
  "foursome",
  "swinger",
  "swingers",
  "swinging",
  "wife swap",
  "wifeswap",
  "wife-swap",
  "cuckold",
  "cuck",
  "cuckquean",
  "pegging",
  "rimming",
  "rimjob",
  "69",
  "sixty nine",
  "sixty-nine",
  "double penetration",
  "dp",
  "facial",
  "facials",
  "milf",
  "gilf",
  "dilf",
  "twink",
  "bear",
  "otter",
  "cub",
  "furry",
  "yiff",
  "yiffy",
  "yiffing",
  "vore",
  "scat",
  "watersports",
  "piss",
  "pissing",
  "golden shower",
  "golden-shower",
  "goldenshower",
  "enema",
  "enemas",
  "prolapse",
  "prolapsing",
  "fisting",
  "fist",
  "fisted",
  "fister",
  "felching",
  "felch",
  "felched",
  "felcher",
  "snowballing",
  "snowball",
  "snowballed",
  "snowballer",
  "cumdump",
  "cum-dump",
  "cum dump",
  "cumslut",
  "cum-slut",
  "cum slut",
  "cumwhore",
  "cum-whore",
  "cum whore",
  "bimbo",
  "shemale",
  "ladyboy",
  "trap",
  "futa",
  "futanari",
  "intersex",
  "hermaphrodite",
  "hermaphrodite",
  "panties",
  "panty",
  "panty sniffing",
  "pantysniffing",
  "panty-sniffing",
  "panty sniffer",
  "pantysniffer",
  "panty-sniffer",
  "panty raid",
  "pantyraid",
  "panty-raid",
  "upskirt",
  "up skirt",
  "up-skirt",
  "downblouse",
  "down blouse",
  "down-blouse",
  "voyeur",
  "voyeurism",
  "exhibitionist",
  "exhibitionism",
  "flasher",
  "flashing",
  "public sex",
  "publicsex",
  "public-sex",
  "dogging",
  "cruising",
  "gloryhole",
  "glory hole",
  "glory-hole",
  "cum",
  "jizz",
  "spooge",
  "spunk",
  "jism",
  "load",
  "loads",
  "ejaculate",
  "ejaculation",
  "ejaculating",
  "masturbate",
  "masturbation",
  "masturbating",
  "jerk off",
  "jerkoff",
  "jerk-off",
  "wank",
  "wanking",
  "wanker",
  "hand job",
  "handjob",
  "hand-job",
  "blow job",
  "blowjob",
  "blow-job",
  "deepthroat",
  "deep throat",
  "deep-throat",
  "gagging",
  "gag",
  "gagged",
  "spitroast",
  "spit roast",
  "spit-roast",
  "anal",
  "analingus",
  "ass",
  "arse",
  "butt",
  "butthole",
  "asshole",
  "arsehole",
  "rimjob",
  "rimming",
  "tits",
  "boobs",
  "breasts",
  "nipples",
  "nipple",
  "areola",
  "tit",
  "teat",
  "teats",
  "chesticles",
  "melons",
  "jugs",
  "rack",
  "knockers",
  "hooters",
  "bazongas",
  "bazooms",
  "funbags",
  "fun bags",
  "fun-bags",
  "penis",
  "penises",
  "cock",
  "cocks",
  "dick",
  "dicks",
  "shaft",
  "phallus",
  "member",
  "wang",
  "dong",
  "pecker",
  "prick",
  "schlong",
  "meat",
  "meatstick",
  "meat stick",
  "meat-stick",
  "balls",
  "testicles",
  "nuts",
  "nut sack",
  "nutsack",
  "nut-sack",
  "scrotum",
  "sack",
  "pussy",
  "pussies",
  "vagina",
  "vaginas",
  "cunt",
  "cunts",
  "twat",
  "snatch",
  "beaver",
  "muff",
  "cooch",
  "coochie",
  "cooter",
  "fanny",
  "gash",
  "slit",
  "clit",
  "clitoris",
  "labia",
  "cameltoe",
  "camel toe",
  "camel-toe",
  "dildo",
  "dildos",
  "vibrator",
  "vibrators",
  "buttplug",
  "butt plug",
  "butt-plug",
  "buttplugs",
  "butt plugs",
  "butt-plugs",
  "strapon",
  "strap on",
  "strap-on",
  "strapons",
  "strap ons",
  "strap-ons",
  "sex toy",
  "sex toys",
  "sextoy",
  "sextoys",
  "sex-toy",
  "sex-toys",
  "porn",
  "porno",
  "pornography",
  "pornographic",
  "hardcore",
  "softcore",
  "xxx",
  "adult",
  "adult video",
  "adult-video",
  "adultvideo",
  "adult movie",
  "adult-movie",
  "adultmovie",
  "adult film",
  "adult-film",
  "adultfilm",
  "sex tape",
  "sex-tape",
  "sextape",
  "sex scene",
  "sex-scene",
  "sexscene",
  "nude",
  "nudes",
  "naked",
  "nakedness",
  "bare",
  "barely legal",
  "barelylegal",
  "barely-legal",
  "underage",
  "under age",
  "under-age",
  "lolita",
  "teen",
  "teens",
  "teenager",
  "teenagers",
  "young girl",
  "young girls",
  "young boy",
  "young boys",
  "schoolgirl",
  "school girl",
  "school-girl",
  "schoolboy",
  "school boy",
  "school-boy",
  "virgin",
  "virgins",
  "deflower",
  "deflowering",
  "incest",
  "incestuous",
  "taboo",
  "taboos",
  "stepmom",
  "step mom",
  "step-mom",
  "stepdad",
  "step dad",
  "step-dad",
  "stepsister",
  "step sister",
  "step-sister",
  "stepbrother",
  "step brother",
  "step-brother",
  "mother son",
  "mother-son",
  "motherson",
  "father daughter",
  "father-daughter",
  "fatherdaughter",
  "brother sister",
  "brother-sister",
  "brothersister",
  "uncle niece",
  "uncle-niece",
  "uncleniece",
  "aunt nephew",
  "aunt-nephew",
  "auntnephew",
  "family sex",
  "family-sex",
  "familysex",
  "creampie",
  "cream pie",
  "cream-pie",
  "cumshot",
  "cum shot",
  "cum-shot",
  "money shot",
  "money-shot",
  "moneyshot",
  "facial",
  "facials",
  "bukkake",
  "gangbang",
  "gang bang",
  "gang-bang",
  "orgy",
  "orgies",
  "threesome",
  "foursome",
  "swinger",
  "swingers",
  "swinging",
  "wife swap",
  "wife-swap",
  "wifeswap",
  "cuckold",
  "cuck",
  "cuckquean",
  "pegging",
  "rimming",
  "rimjob",
  "69",
  "sixty nine",
  "sixty-nine",
  "double penetration",
  "dp",
  "facial",
  "facials",
  "milf",
  "gilf",
  "dilf",
  "twink",
  "bear",
  "otter",
  "cub",
  "furry",
  "yiff",
  "yiffy",
  "yiffing",
  "vore",
  "scat",
  "watersports",
  "piss",
  "pissing",
  "golden shower",
  "golden-shower",
  "goldenshower",
  "enema",
  "enemas",
  "prolapse",
  "prolapsing",
  "fisting",
  "fist",
  "fisted",
  "fister",
  "felching",
  "felch",
  "felched",
  "felcher",
  "snowballing",
  "snowball",
  "snowballed",
  "snowballer"
  ,
  // More for websites
  "pornhub",
  "xvideos",
  "xnxx",
  "redtube",
  "youporn",
  "brazzers",
  "bangbros",
  "onlyfans",
  "chaturbate",
  "camsoda",
  "myfreecams",
  "cam4",
  "livejasmin",
  "bongacams",
  "stripchat",
  "adultfriendfinder",
  "ashleymadison",
  "fetlife",
  "alt.com",
  "swinglifestyle",
  "sdc.com",
  "escortdirectory",
  "escortfinder",
  "escortreviews",
  "escortads",
  "escortbabylon",
  "eros.com",
  "backpage",
  "craigslist personals",
  "craigslist adult",
  "craigslist sex",
  "craigslist escorts",
  "craigslist erotic",
  "craigslist hookup",
  "craigslist casual",
  "craigslist w4m",
  "craigslist m4w",
  "craigslist m4m",
  "craigslist w4w",
  "seekingarrangement",
  "seeking.com",
  "sugardaddy.com",
  "sugarbabies.com",
  "sugarbook",
  "adultwork",
  "swisscows",
  "tnaflix",
  "spankbang",
  "motherless",
  "hclips",
  "efukt",
  "rule34",
  "rule 34",
  "leakgirls",
  "leakedfans",
  "leakthis",
  "leak",
  "leaks",
  "leaked",
  "leakeds",
  "leakgirls.com",
  "leakedfans.com",
  "leakthis.com",
  "camwhores",
  "camwhores.tv",
  "camwhores.com",
];
